### ISSUE TITLE
How to obtain the instance-level motion segmentation mask for each moving object?

### ISSUE THREAD

**Issue by AzulYang** [zpbao/Discovery_Obj_Move#10]
In addition, are the motion groundtruth in the KITTI dataset manually annotated?

**Comment by zpbao** [comment]
Hi,

For the motion segments, please refer to [this](https://github.com/achalddave/segment-any-moving) repo. 

For KITTI, there is no motion GT. If you mean the test images, they are from the official [semantic and instance segmentation evaluation](https://www.cvlibs.net/datasets/kitti/eval_semantics.php) task.

Thanks,
Zhipeng

**Comment by AzulYang** [comment]
Thanks a lot!
I found that you have released the masks of KITTI ,and I had already downloaded KITTI-segs and KITTI-test.I don’t quite understand the usage in the KITTI-segs caused the majority are black.

**Comment by AzulYang** [comment]
Are the masks in KITTI-segs for all instances?Rather than the mask of the moving object?

**Comment by zpbao** [comment]
Hi, 

the masks for KITTI are generated using [this](https://github.com/achalddave/segment-any-moving) repo. They should be for moving objects. 

For the question of the majority being black, we only supervise our model with matched masks, so as long as the motion segments can find some meaningful moving signal it could help.

**Comment by AzulYang** [comment]
Sorry to bother you again, regarding the mentioned use of all 147 videos in KITTI for training, is there a download link for these? Is the video available in google drive with the name test_video?Cause it takes about 3 hours for me to download the files in google drive.

**Comment by zpbao** [comment]
Hi, 

You can find the URLs at the [official KITTI webpage](https://www.cvlibs.net/datasets/kitti/).

Moreover, I also know some ex-collaborators have released a set of KITTI raw data at [this repo](https://github.com/TRI-ML/packnet-sfm), you can download their KITTI dataset via:

curl -s https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/datasets/KITTI_raw.tar | tar -xv -C /data/datasets/

Notice that I have not downloaded their dataset before but I assume the videos should be the same.

Best,
Zhipeng
