### ISSUE TITLE
Missing additional data?

### ISSUE THREAD

**Issue by kimhc6028** [zpbao/Discovery_Obj_Move#2]
Thank you for sharing code of your nice work!
I am trying to train with the TRI-PD dataset, but I cannot find "additional annotations" from the link on the readme.
I understand the annotations are not necessary for the training itself, but can you please check if the annotations are available?
Thank you!

**Comment by Brummi** [comment]
Thank you also from me!
I would also be interested in this!

**Comment by Brummi** [comment]
Also, it seems that the downloadable data for TRI-PD only contains 5 scenes, while paper states that around 150 scenes were used for training.

**Comment by zpbao** [comment]
Hi Kimhc and Felix, 

Thanks for your interest! We have updated the full PD dataset link and also uploaded the additional data for PD. Let me know if there is any data we are missing! Thanks!

Regards,
Zhipeng
