### ISSUE TITLE
Training Time & Pretrained model

### ISSUE THREAD

**Issue by Brummi** [zpbao/Discovery_Obj_Move#3]
Hi Zhipeng,

thanks again for providing the data and the code!
I just wondered whether you could give me any info on how much GPU RAM you needed for training and how long it takes to train the model from scratch.

Many thanks in advance :D.
Best,
Felix

**Comment by zpbao** [comment]
Hi Felix,

Thanks for your interest! The training time will be around 3 days for 500 epochs as I remembered (with 4 A100 GPU and each ~16GB memory). For the pre-trained model, we are running with the data augmentation trick with SAVi++ and will provide one ASAP. Will reply this thread when I upload one. Thanks!

Cheers,
Zhipeng

**Comment by zpbao** [comment]
Hi Felix,

Sorry for the really late reply, just update the repo and provide all the necessary codes and models. Please check.

Thanks,
Zhipeng
