### ISSUE TITLE
Truncated archives (TRI-PD dataset)

### ISSUE THREAD

**Issue by mtangemann** [zpbao/Discovery_Obj_Move#7]
Dear Zhipeng,

Thank you for making the TRI-PD dataset available! I have however problems with using the data: archives 14-19 are truncated (`tar: Unexpected EOF in archive`). I tried downloading the files again but got the same error.

Can you double check whether the data was uploaded correctly? Maybe you could also publish checksums of your local files so that the download can be verified.

Thank you,
Matthias

**Comment by zpbao** [comment]
Hi Matthias, 

Thanks for your message! The PD dataset is mounted at TRI's AWS and I have reported the issue to them. However, I manually tried archives 15 and it worked perfectly. I wonder if the issue is caused by the download process? I am also double-checking the other archives. 

Will reply when I got any update and also hope the re-downloading can help resolve the issue.

Regards,
Zhipeng

**Comment by zpbao** [comment]
Ah, it indeed shows the error message at the end! Thanks for letting us know and will reach out soon.

**Comment by mtangemann** [comment]
Hi Zhipeng,

Thanks for looking into it! Can you estimate when you'll have time to re-upload the archives?

Best,
Matthias

**Comment by zpbao** [comment]
Hi mtangemann,

Sorry for the really late reply. Currently, the links are still broken... 

However, I provided a simplified TRI-PD dataset with RGB, flow, and masks. Not sure if they are enough for your work. 

I do have the full dataset but I cannot release it by myself... If you feel interested, please directly contact me through email and I may find some way to share the full dataset with you. I am also trying to ask if I could release it by myself with the latest work and will keep updating the readme files for the dataset issue.

Thanks,
Zhipeng

**Comment by mtangemann** [comment]
Hi Zhipeng,

Thank you for the update, that helps a lot. The simplified TRI-PD dataset is enough for my current work.

For future projects it would be great to also have, e.g., the depth maps. So if there's a way for you update the full dataset release that would be great.

Best,
Matthias

**Comment by zpbao** [comment]
Hi Matthias,

I am trying to release the full set with a newer work and will definitely keep updating the readme and keep you noted. Thanks for your interest!

Regards,
Zhipeng

**Comment by zpbao** [comment]
Hi Matthias, 

The full version with additional depth and semantic masks is released to google drive. Check the updated readme for details. 

Thanks,
Zhipeng

**Comment by mtangemann** [comment]
Great! Thanks a lot for the update Zhipeng.
